[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/BartekDaniluk/Big_Data/blob/main/Pandas%20cz.2.ipynb)

# Agregacja danych
Jest to niezbędna czynność procesu analizy danych i badań eksploracyjnych. Pozwala na sprawne obliczenie najważniejszych statystyk danych takich jak średnia, mediana, kwartyle itd. oraz ich grupowanie w celu dostrzeżenia ewentualnych trendów w danych.

In [9]:
import pandas as pd
import numpy as np
import plotly

Metoda **head** wyświetla podaną ilość wierszy (domyślnie 5) od początku danego obiektu DataFrame.

In [10]:
df = pd.DataFrame(np.random.randn(1000, 10), columns = [f'Col_{x+1}' for x in range(10)])
df.head()

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10
0,0.075951,-0.663305,2.023887,0.695437,-0.306346,-0.366717,-0.923608,-0.920983,0.783432,1.200463
1,0.439421,0.602620,-0.683383,0.677639,0.438421,-0.805378,-0.673691,-0.543588,-2.428617,1.409894
2,0.118967,-1.043770,-1.323231,0.756619,-0.192448,0.320638,-0.431943,0.227985,-0.645560,2.443236
3,0.037451,-0.706440,-1.151941,-0.319575,0.628116,0.089089,-1.417442,0.081071,-0.484037,-0.105225
4,0.559001,-0.962895,0.498976,0.041248,-1.638196,-0.130859,0.360889,1.439058,-0.460622,-0.559590

**tail** to to samo co **head** tylko że od końca.

In [11]:
df.tail()

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10
995,1.722831,1.166078,0.820208,-0.351952,-0.242461,-0.284163,0.493539,0.547989,-0.516358,0.988580
996,-1.974047,-0.462448,-0.453613,-1.304567,1.877221,0.915666,0.953321,-1.921340,-2.152320,-0.495462
997,0.122370,-0.305462,0.864273,-0.928088,0.401524,1.414704,-1.956808,1.281581,-0.442686,1.838428
998,-0.176523,0.449581,-0.331039,1.654861,-0.849914,-0.384138,0.163019,-0.252305,-0.205857,-0.532063
999,1.235430,1.257815,-1.964778,0.531461,-0.055303,-0.199677,1.807561,-0.182436,1.572927,0.524583

Tak jak w przypadku **np.ndarray** funkcje agregacyjne zwracają dla obiektu **pd.Series** pojedynczą wartość.

In [12]:
pd.Series(np.arange(100)).sum(), pd.Series(np.arange(100)).median(), df['Col_2'].mean()

(np.int64(4950), 49.5, np.float64(-0.004463180243388478))

Jeśli wywołane one są dla obiektu **pd.DataFrame** zwracają one wartości dla każdej z kolumn. Jeśli określimy argument **axis** możemy agregować każdy rząd.

In [13]:
df.median()

Col_1     0.014396
Col_2    -0.027783
Col_3    -0.042161
Col_4     0.030075
Col_5     0.006195
Col_6    -0.035556
Col_7     0.001174
Col_8     0.050980
Col_9     0.024002
Col_10   -0.018210
dtype: float64

In [14]:
df.mean(axis = 'columns')

0      0.159821
1     -0.156666
2      0.023049
3     -0.334893
4     -0.085299
         ...
995    0.434429
996   -0.501759
997    0.228984
998   -0.046438
999    0.452758
Length: 1000, dtype: float64

Jedną z najpopularniejszych metod obiektu pd.DataFrame jest **describe**. Opisuje ona wszystkie kolumny numeryczne za pomocą przydatnych metryk jak średnia, odchylenie standardowe, w.min. 25%, 50%, 75% (kolejno pierwszy drugi i trzeci kwartyl) i w.max.

In [15]:
df.describe()

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.046921,-0.004463,-0.007398,0.071745,0.012721,-0.019543,0.013356,0.035105,0.024405,-0.009056
std,0.978504,1.004885,1.017281,1.004878,0.996130,0.992657,1.004440,0.982149,0.989810,0.974688
min,-3.192499,-3.195837,-3.842758,-3.539613,-3.010777,-2.993477,-3.428669,-3.244851,-2.774462,-3.427428
25%,-0.575141,-0.708813,-0.712302,-0.612645,-0.646471,-0.674836,-0.658074,-0.641812,-0.637835,-0.636006
50%,0.014396,-0.027783,-0.042161,0.030075,0.006195,-0.035556,0.001174,0.050980,0.024002,-0.018210
75%,0.669357,0.598581,0.694233,0.738845,0.658525,0.695562,0.636341,0.702081,0.718181,0.643284
max,3.135030,3.822955,4.168578,3.252296,3.643494,2.799631,4.117724,3.382708,3.000502,3.386954

# Podsumowanie funkcji agregujacych


| Funkcja      | Opis                                                                                       | Przykład                         |
|--------------|--------------------------------------------------------------------------------------------|----------------------------------|
| `sum()`      | Suma wartości w każdej kolumnie                                                            | `df['kolumna'].sum()`            |
| `mean()`     | Średnia wartość w każdej kolumnie                                                          | `df['kolumna'].mean()`           |
| `count()`    | Liczba niepustych wartości w każdej kolumnie                                               | `df['kolumna'].count()`          |
| `min()`      | Minimalna wartość w każdej kolumnie                                                        | `df['kolumna'].min()`            |
| `max()`      | Maksymalna wartość w każdej kolumnie                                                       | `df['kolumna'].max()`            |
| `std()`      | Odchylenie standardowe wartości w każdej kolumnie                                          | `df['kolumna'].std()`            |
| `var()`      | Wariancja wartości w każdej kolumnie                                                       | `df['kolumna'].var()`            |
| `median()`   | Mediana wartości w każdej kolumnie                                                         | `df['kolumna'].median()`         |
| `mad()`      | Średnie bezwzględne odchylenie od średniej (mean absolute deviation)                       | `df['kolumna'].mad()`            |
| `first()`    | Pierwsza wartość w każdej kolumnie                                                         | `df['kolumna'].first()`          |
| `last()`     | Ostatnia wartość w każdej kolumnie                                                         | `df['kolumna'].last()`           |
| `agg()`      | Możliwość zastosowania wielu funkcji agregujących na raz, w tym niestandardowych funkcji   | `df['kolumna'].agg(['sum', 'mean'])` |

Za pomocą metody **info** możemy wyświetlić informacje o naszym zbiorze danych, a przede wszystkim typy danych każdej z kolumn. Jak widać w nowym zbiorze danych mamy parę kolumn po których moglibyśmy pogrupować nasze dane.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col_1   1000 non-null   float64
 1   Col_2   1000 non-null   float64
 2   Col_3   1000 non-null   float64
 3   Col_4   1000 non-null   float64
 4   Col_5   1000 non-null   float64
 5   Col_6   1000 non-null   float64
 6   Col_7   1000 non-null   float64
 7   Col_8   1000 non-null   float64
 8   Col_9   1000 non-null   float64
 9   Col_10  1000 non-null   float64
dtypes: float64(10)
memory usage: 78.3 KB

# Grupowanie danych

Często podczas przetwarzania zbioru danych będziemy chcieli pogrupować nasze dane na podstawie różnych kolumn, np. jeśli są to kolumny kategoryczne (płeć, pełnoletni/niepełnoletni, paragon/faktura). Służy do tego metoda **groupby**. Dzieli ona dane na podstawie danych kolumn (jednej lub więcej) dzięki czemu możemy wykonywać różne operacje, jak poznane wcześniej agregacje tylko na danej 'grupie' danych.

Posłużę się tutaj zbiorem danych **tips** zawartego w module plotly.data.

In [17]:
df_tips = plotly.data.tips(pretty_names = True)
df_tips.head()

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4

Jak widać sama metoda nie zwraca DataFrame a obiekt DataFrameGroupBy. To właśnie na tym obiekcie wykonujemy pożądane operacje.

In [18]:
df_tips.groupby('Payer Gender')

Możemy np. dowiedzieć się że Panowie średnio dają większe (nie o wiele ale nadal) napiwki. Realistycznie rzecz biorąc taką różnice można potraktować jako błąd statystyczny.

In [19]:
df_tips.groupby('Payer Gender')['Tip'].mean()

Payer Gender
Female    2.833448
Male      3.089618
Name: Tip, dtype: float64

Grupować możemy również po wielu kolumnach. Czyli palące panie dają więcej niż nie palące, a najwięcej 'napiwkują' niepalący panowie. Ale czy najczęściej?.

In [20]:
df_tips.groupby(['Payer Gender', 'Smokers at Table'])['Tip'].mean()

Payer Gender  Smokers at Table
Female        No                  2.773519
              Yes                 2.931515
Male          No                  3.113402
              Yes                 3.051167
Name: Tip, dtype: float64

Nie, jak widać jeśli liczymy na napiwek, unikamy dymu, albo ryzykujemy i idziemy do palących panów.

In [21]:
df_tips.groupby(['Payer Gender', 'Smokers at Table'])[['Tip', 'Total Bill']].sum()

                                  Tip  Total Bill
Payer Gender Smokers at Table
Female       No                149.77      977.68
             Yes                96.74      593.27
Male         No                302.00     1919.75
             Yes               183.07     1337.07

Możemy również wykorzystywać wiele funkcji agregacyjnych naraz lub nawet tworzyć własne. W celu wykorzystania ich na naszej grupę korzystamy z metody **agg()**, ponadto umożliwia ona użycie różnych funkcji dla różnych kolumn.

In [22]:
df_tips.groupby('Party Size').agg({'Total Bill': ['sum', 'count'],
                                   'Tip': 'mean'})

           Total Bill             Tip
                  sum count      mean
Party Size
1               28.97     4  1.437500
2             2565.89   156  2.582308
3              884.55    38  3.393158
4             1058.70    37  4.135405
5              150.34     5  4.028000
6              139.32     4  5.225000

Czyli najwięcej wydały pary, a średnio największy napiwek dają grupy 6-cio osobowe. Wracając do płci, zobaczmy ile % całego rachunku stanowią napiwki. Wykorzystamy do tego własną funkcję.

In [23]:
grouped_tips = df_tips.groupby('Payer Gender').agg(
    Total_Bill_Sum=('Total Bill', 'sum'),
    Tip_sum=('Tip', 'sum')
)
grouped_tips

              Total_Bill_Sum  Tip_sum
Payer Gender
Female               1570.95   246.51
Male                 3256.82   485.07

In [24]:
grouped_tips['tip percentage'] = (grouped_tips['Tip_sum'] / grouped_tips['Total_Bill_Sum']) * 100
grouped_tips

              Total_Bill_Sum  Tip_sum  tip percentage
Payer Gender
Female               1570.95   246.51       15.691779
Male                 3256.82   485.07       14.893976

Warto jeszcze wspomnieć że jeśli mamy do czynienia z cechami takimi jak płeć pandas obsługuje typ **Categorical**. Zmienne tego typu mogą przyjąć określoną ilość wartości np. Płeć - Mężczyzna, Kobieta, Diagnoza - Chory, Zdrowy itp. Ponadto typ ten może mieć określoną kolejność.

In [25]:
df_tips['Payer Gender'] = df_tips['Payer Gender'].astype('category')
df_tips.dtypes

Total Bill           float64
Tip                  float64
Payer Gender        category
Smokers at Table      object
Day of Week           object
Meal                  object
Party Size             int64
dtype: object

# Apply
Jest to kelejna bardzo przydatna metoda pozwalająca na 'zastosowanie' danej funkcji wzdłuż danej osi ramki danych.

In [26]:
df = pd.DataFrame(np.arange(0, 100).reshape(20, 5), columns=[f'Col_{x + 1}' for x in range(5)])
df.head()

   Col_1  Col_2  Col_3  Col_4  Col_5
0      0      1      2      3      4
1      5      6      7      8      9
2     10     11     12     13     14
3     15     16     17     18     19
4     20     21     22     23     24

In [27]:
def half(number):
  return number / 2

df.apply(half).head()

   Col_1  Col_2  Col_3  Col_4  Col_5
0    0.0    0.5    1.0    1.5    2.0
1    2.5    3.0    3.5    4.0    4.5
2    5.0    5.5    6.0    6.5    7.0
3    7.5    8.0    8.5    9.0    9.5
4   10.0   10.5   11.0   11.5   12.0

Jako że musimy przekazać funkcje, możemy oczywiście przekazać lambdę.

In [28]:
df.apply(lambda x: x * 4).head()

   Col_1  Col_2  Col_3  Col_4  Col_5
0      0      4      8     12     16
1     20     24     28     32     36
2     40     44     48     52     56
3     60     64     68     72     76
4     80     84     88     92     96

Za pomocą argumentu **axis** określamy wzdłuż czego stosujemy funkcję. 0 - kolumny, 1 - rzędy.

In [29]:
df.apply(lambda row: row.sum(), axis = 1)

0      10
1      35
2      60
3      85
4     110
5     135
6     160
7     185
8     210
9     235
10    260
11    285
12    310
13    335
14    360
15    385
16    410
17    435
18    460
19    485
dtype: int64

# Zwektoryzowane operacje na Stringach (Vectorized String Operations)
Za ich pomocą możemy manipulować wszystkimi stringami obiektu pd.Series bez potrzeby żadnych pętli, coś jak broadcasting operacji matematycznych. Aby to zrobić będziemy korzystać z pola (accesosor) **.str**. Ważnym aspektem tego podejścia jest to że jest ono nie wrażliwe na wartości brakujące.

In [30]:
df = pd.DataFrame({
    'Imiona' : ['John Doe',
                'Mark Marcusson',
                'Bartłoiej Daniluk',
                'Jan Kowalski',
                'Janina Kowal',
                'Lorem Ispum',
                'Test Testowski',
                'Unit Testson'
})
df

                                  Imiona
0                               John Doe
1                         Mark Marcusson
2                      Bartłoiej Daniluk
3                           Jan Kowalski
4                           Janina Kowal
5  Lorem IspumTest TestowskiUnit Testson

Za pomocą wcześniej wspomnianego akcesora możemy wywoływać na funkcje po kolei na każdej wartości.

## Cheat Sheet funkcji, działają tak samo jak w pythonie

| Metoda Pandas `str`     | Opis                                              |
|--------------------------|---------------------------------------------------|
| `str.lower()`            | Zwraca string w formie małych liter.            |
| `str.upper()`            | Zwraca string w formie wielkich liter.          |
| `str.title()`            | Zwraca string z wielką literą na początku każdego słowa. |
| `str.capitalize()`       | Zwraca string z wielką literą na początku.      |
| `str.strip()`            | Usuwa białe znaki z początku i końca stringu.   |
| `str.lstrip()`           | Usuwa białe znaki z początku stringu.           |
| `str.rstrip()`           | Usuwa białe znaki z końca stringu.              |
| `str.replace()`          | Zastępuje podciąg innym podciągiem.              |
| `str.split()`            | Dzieli string na listę podciągów.               |
| `str.join()`             | Łączy elementy iterowalnego obiektu w jeden string. |
| `str.find()`             | Zwraca indeks pierwszego wystąpienia podciągu.   |
| `str.rfind()`            | Zwraca indeks ostatniego wystąpienia podciągu.   |
| `str.index()`            | Zwraca indeks pierwszego wystąpienia podciągu (wywołuje błąd, jeśli nie znaleziono). |
| `str.rindex()`           | Zwraca indeks ostatniego wystąpienia podciągu (wywołuje błąd, jeśli nie znaleziono). |
| `str.count()`            | Zlicza wystąpienia podciągu w stringu.          |
| `str.startswith()`       | Sprawdza, czy string zaczyna się od danego podciągu. |
| `str.endswith()`         | Sprawdza, czy string kończy się danym podciągiem. |
| `str.len()`              | Zwraca długość stringu.                         |
| `str.isalpha()`          | Sprawdza, czy wszystkie znaki w stringu są literami. |
| `str.isdigit()`          | Sprawdza, czy wszystkie znaki w stringu są cyframi. |
| `str.isspace()`          | Sprawdza, czy wszystkie znaki w stringu są białymi znakami. |
| `str.isalnum()`          | Sprawdza, czy wszystkie znaki w stringu są literami lub cyframi. |

In [31]:
df['Imiona'].str.upper()

0                                 JOHN DOE
1                           MARK MARCUSSON
2                        BARTŁOIEJ DANILUK
3                             JAN KOWALSKI
4                             JANINA KOWAL
5    LOREM ISPUMTEST TESTOWSKIUNIT TESTSON
Name: Imiona, dtype: object

In [32]:
df['Imiona'].str.startswith('B')

0    False
1    False
2     True
3    False
4    False
5    False
Name: Imiona, dtype: bool

List slicing również odnosi się do poszczególnych stringów

In [52]:
df['Imiona'].str.lower().capitalize()

0                                 John doe
1                           Mark marcusson
2                        Bartłoiej daniluk
3                             Jan kowalski
4                             Janina kowal
5    Lorem ispumtest testowskiunit testson
Name: Imiona, dtype: object

In [33]:
df['Imiona'].str[0:3]

0    Joh
1    Mar
2    Bar
3    Jan
4    Jan
5    Lor
Name: Imiona, dtype: object

Ponadto pandas zawiera parę metod które przyjmują wyrażenia regularne (regex). Działają identycznie jak te z modułu **re**.

In [34]:
df['Imiona'].str.extract(r'.*(on|uk)')

     0
0  NaN
1   on
2   uk
3  NaN
4  NaN
5   on

# Pivot Tables - Tabele przestawne

In [35]:
df_tips.head()

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4

Aby utworzyć tabelę przestawną wykorzystujemy funkcję **pivot_table**. Musimy podać obiekt DataFeame z którego chcemy ją utworzyć, wartości jakie do niej przekażemy, co będzie naszym nowym indeksem, co kolumnami i jaką funkcję agregującą wykorzystamy. **fill_value** określa czym są wypełnianie ewentualne wartości puste.

In [36]:
pivot_table = pd.pivot_table(df_tips, values = 'Tip', index = 'Meal', columns = 'Party Size', aggfunc = 'mean', fill_value = 0)
pivot_table

Party Size      1         2      3       4      5    6
Meal
Dinner      1.000  2.661923  3.490  4.1225  3.785  5.0
Lunch       1.875  2.423077  2.754  4.2180  5.000  5.3

In [37]:
pivot_table = pd.pivot_table(df_tips, values = ['Tip', 'Total Bill'], index = 'Meal', columns = 'Party Size', aggfunc = ['mean', 'sum'], fill_value = 0)
pivot_table

             mean                                                             \
              Tip                                      Total Bill
Party Size      1         2      3       4      5    6          1          2
Meal
Dinner      1.000  2.661923  3.490  4.1225  3.785  5.0      5.160  17.228654
Lunch       1.875  2.423077  2.754  4.2180  5.000  5.3      9.325  14.886731

                                  ...     sum                                  \
                                  ...     Tip                      Total Bill
Party Size          3          4  ...       3       4      5     6          1
Meal                              ...
Dinner      23.997879  28.404688  ...  115.17  131.92  15.14   5.0      10.32
Lunch       18.524000  29.950000  ...   13.77   21.09   5.00  15.9      18.65



Party Size        2       3       4       5      6
Meal
Dinner      1791.78  791.93  908.95  109.15  48.17
Lunch        774.11   92.62  149.75   41.19  91.15

[2 rows x 24 columns]

In [38]:
df_tips.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [39]:
df_tips.loc[-1] = df_tips.loc[1].copy()
df_tips.index += 1
df_tips.sort_index()

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
0,10.34,1.66,Male,No,Sun,Dinner,3
1,16.99,1.01,Female,No,Sun,Dinner,2
2,10.34,1.66,Male,No,Sun,Dinner,3
3,21.01,3.50,Male,No,Sun,Dinner,3
4,23.68,3.31,Male,No,Sun,Dinner,2
...,...,...,...,...,...,...,...
240,29.03,5.92,Male,No,Sat,Dinner,3
241,27.18,2.00,Female,Yes,Sat,Dinner,2
242,22.67,2.00,Male,Yes,Sat,Dinner,2
243,17.82,1.75,Male,No,Sat,Dinner,2
244,18.78,3.00,Female,No,Thur,Dinner,2

In [40]:
df_tips.duplicated()

1      False
2      False
3      False
4      False
5      False
       ...
241    False
242    False
243    False
244    False
0       True
Length: 245, dtype: bool

In [41]:
rows_to_concat = df_tips.loc[10:20].copy()
pd.concat((rows_to_concat, df_tips), ignore_index=True)

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
0,14.78,3.23,Male,No,Sun,Dinner,2
1,10.27,1.71,Male,No,Sun,Dinner,2
2,35.26,5.00,Female,No,Sun,Dinner,4
3,15.42,1.57,Male,No,Sun,Dinner,2
4,18.43,3.00,Male,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
251,27.18,2.00,Female,Yes,Sat,Dinner,2
252,22.67,2.00,Male,Yes,Sat,Dinner,2
253,17.82,1.75,Male,No,Sat,Dinner,2
254,18.78,3.00,Female,No,Thur,Dinner,2
255,10.34,1.66,Male,No,Sun,Dinner,3

In [42]:
rows_to_concat

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
10,14.78,3.23,Male,No,Sun,Dinner,2
11,10.27,1.71,Male,No,Sun,Dinner,2
12,35.26,5.00,Female,No,Sun,Dinner,4
13,15.42,1.57,Male,No,Sun,Dinner,2
14,18.43,3.00,Male,No,Sun,Dinner,4
15,14.83,3.02,Female,No,Sun,Dinner,2
16,21.58,3.92,Male,No,Sun,Dinner,2
17,10.33,1.67,Female,No,Sun,Dinner,3
18,16.29,3.71,Male,No,Sun,Dinner,3
19,16.97,3.50,Female,No,Sun,Dinner,3
20,20.65,3.35,Male,No,Sat,Dinner,3

In [43]:
df_tips_2 = df_tips[['Total Bill', 'Tip', 'Party Size']].copy()
df_tips_2.head()

   Total Bill   Tip  Party Size
1       16.99  1.01           2
2       10.34  1.66           3
3       21.01  3.50           3
4       23.68  3.31           2
5       24.59  3.61           4

In [44]:
pd.merge(df_tips, df_tips_2, how = 'left', on = 'Party Size')

,Total Bill_x,Tip_x,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size,Total Bill_y,Tip_y
0,16.99,1.01,Female,No,Sun,Dinner,2,16.99,1.01
1,16.99,1.01,Female,No,Sun,Dinner,2,23.68,3.31
2,16.99,1.01,Female,No,Sun,Dinner,2,8.77,2.00
3,16.99,1.01,Female,No,Sun,Dinner,2,15.04,1.96
4,16.99,1.01,Female,No,Sun,Dinner,2,14.78,3.23
...,...,...,...,...,...,...,...,...,...
27278,10.34,1.66,Male,No,Sun,Dinner,3,15.98,3.00
27279,10.34,1.66,Male,No,Sun,Dinner,3,15.69,3.00
27280,10.34,1.66,Male,No,Sun,Dinner,3,35.83,4.67
27281,10.34,1.66,Male,No,Sun,Dinner,3,29.03,5.92
27282,10.34,1.66,Male,No,Sun,Dinner,3,10.34,1.66

In [45]:
df_multi = df_tips.set_index(['Payer Gender', 'Smokers at Table'])

In [46]:
df_multi.loc['Male', 'No']

/tmp/ipython-input-1805406739.py:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc['Male', 'No']

                               Total Bill   Tip Day of Week    Meal  \
Payer Gender Smokers at Table
Male         No                     10.34  1.66         Sun  Dinner
             No                     21.01  3.50         Sun  Dinner
             No                     23.68  3.31         Sun  Dinner
             No                     25.29  4.71         Sun  Dinner
             No                      8.77  2.00         Sun  Dinner
...                                   ...   ...         ...     ...
             No                     10.77  1.47         Sat  Dinner
             No                     10.07  1.25         Sat  Dinner
             No                     29.03  5.92         Sat  Dinner
             No                     17.82  1.75         Sat  Dinner
             No                     10.34  1.66         Sun  Dinner

                               Party Size
Payer Gender Smokers at Table
Male         No                         3
             No                         3
             No                         2
             No                         4
             No                         2
...                                   ...
             No                         2
             No                         2
             No                         3
             No                         2
             No                         3

[98 rows x 5 columns]

In [47]:
df_tips.head()

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size
1,16.99,1.01,Female,No,Sun,Dinner,2
2,10.34,1.66,Male,No,Sun,Dinner,3
3,21.01,3.50,Male,No,Sun,Dinner,3
4,23.68,3.31,Male,No,Sun,Dinner,2
5,24.59,3.61,Female,No,Sun,Dinner,4

In [48]:
df_tips.assign(bill_per_head=lambda df: df['Total Bill'] / df['Party Size'],
          tip_per_head=lambda df: df['Tip'] / df['Party Size'])

,Total Bill,Tip,Payer Gender,Smokers at Table,Day of Week,Meal,Party Size,bill_per_head,tip_per_head
1,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,0.505000
2,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,0.553333
3,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,1.166667
4,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,1.655000
5,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,0.902500
...,...,...,...,...,...,...,...,...,...
241,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,1.000000
242,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,1.000000
243,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,0.875000
244,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,1.500000
0,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,0.553333